### ISSUE TITLE
The home page has a button to customize the game before creating a new room.

### ISSUE THREAD

**Issue by Yuying8777** [sopra-fs24-group-27/sopra-fs24-group-27-client#38]

**Comment by YatingPan** [comment]
Completed with commit [0b51e4b8ae93c40a9d60e88536f04210f531cb1f](https://github.com/sopra-fs24-group-27/sopra-fs24-group-27-client/commit/0b51e4b8ae93c40a9d60e88536f04210f531cb1f)
